# Generated by Django 2.2.5 on 2019-09-04 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'front user',
                'verbose_name_plural': 'front users',
            },
        ),
        migrations.CreateModel(
            name='CustomerUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='customer', serialize=False, to='accounts.FrontUser')),
                ('tel', models.CharField(max_length=20, verbose_name='電話番号')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.frontuser',),
        ),
        migrations.CreateModel(
            name='SupporterUser',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='supporter', serialize=False, to='accounts.FrontUser')),
                ('organization', models.CharField(max_length=64, verbose_name='組織')),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.frontuser',),
        ),
    ]
