# Generated by Django 3.0.5 on 2020-04-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customeruser',
            options={'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
        migrations.AlterModelOptions(
            name='supporteruser',
            options={'verbose_name': 'Supporter', 'verbose_name_plural': 'Supporters'},
        ),
    ]
